### PR TITLE
Adding support for periodic noise 2d/3d

### PR DESCRIPTION
**Pull request by realisim**
- Not all noise can be periodic, this commit adds support to Perlin,
  PerlinFractal and Cellular. In theory Simplex and SimplexFractal should
  be triavial, but it did not work...
- added GetPeriodicNoise function to sample periodic noise.
- Perlin, PerlinFractal and Cellular (2D/3D) are supported by GetPeriodicNoise()

### CODE REVIEW

**Comment by Auburns** [comment]
What is the performance impact when not using periodic noise?

**Comment by realisim** [comment]
It does have an impact... here are the numbers:

Test is as follow:
Ran 1000 times to generate 512x512 image with the following code:
```
const int numTests = 1000;

Timer timer;
Statistics stats;

FastNoise fn;
fn.SetNoiseType(FastNoise::PerlinFractal);
fn.SetFractalType(FastNoise::FBM);
fn.SetFractalOctaves(3);
fn.SetFractalLacunarity(2.0f);
fn.SetFractalGain(0.5f);
fn.SetFrequency(0.02f);

float noiseValue;

// non periodic noise    
for (int i = 0; i < numTests; ++i)
{
    timer.start();
    for (int sy = 0; sy < 512; ++sy)
    {
        for (int sx = 0; sx < 512; ++sx)
        {
            noiseValue = fn.GetNoise((float)sx, (float)sy );                
        }
    }
    stats.add(timer.elapsed());
}
printf("performance non periodic noise\n %s\n", stats.toCsv().c_str());
```

results with your master branch (time in seconds.)
```
-------------------------------------------------------------------------------------
performance non periodic noise with master branch

Number of samples, average,    minimum,    maximum,    standard deviation
1000,              0.00936758, 0.00930322, 0.0185114,  0.000448685
```

results with modifications for periodic noise.
```
-------------------------------------------------------------------------------------
performance non periodic noise with modifications from Realisim

Number of samples, average,    minimum,    maximum,    standard deviation
1000,              0.010943,   0.0108808,  0.0142765,  0.000154578
```

**Comment by Auburns** [comment]
Hmm, that is a decent performance hit. Can you try making it branch free by using bitwise & instead of %, it would limit it to powers of 2 tiling but I think thats ok.

**Comment by realisim** [comment]
I agree it is quite a hit.

Power of two period might be ok, but we prefer keeping the flexibility of non power of two period.

If we are looking for performance a better option would be to leave everything has it was and overload the necessary functions for periodic noise... Thus the performance hit would happen only if a periodic noise is computed...

Something like this:
```
FN_DECIMAL SinglePerlinFractalFBM(FN_DECIMAL x, FN_DECIMAL y) const;
FN_DECIMAL SinglePerlinFractalFBM(FN_DECIMAL x, FN_DECIMAL y, int px, int py) const;
...
```
This implies a bit of code duplication...

I didn't do it that way simply because I did not want to duplicate code. I am more comfortable with the ease of maintenance than raw performance, for our particular usage. 

FastNoise is fast and meant to be, so of course it is not acceptable to have ~10% loss. I do not have allocated time to make more modifications in the short term, so I believe we can reject the pull request. I just thought you might be interested in seeing it. Sadly, it is not fast enough :)

**Pull request closed without merging**
